### ISSUE TITLE
Suggestion: optimize time-to-first-note

### ISSUE THREAD

**Issue by uniphil** [Kortaggio/mobile-notes#4]
What if the "Add Note" button was connected to an initial note textarea, which would be saved as the new note? On page load, the cursor could be auto-focused on that textarea, so I could start typing as soon as the page loads, and then tab-enter to save it.

**Comment by billmei** [comment]
Good idea! The original intention of this app is for it to work on mobile browsers&mdash;so unfortunately I don't want a keyboard to pop up right away on page load and block half of content while preventing the user from scrolling. Maybe in the future I'll use some `@media` queries to separate out desktop users.

**Comment by uniphil** [comment]
ah fair enough
